= Division of Work

This section outlines the distribution of responsibilities between the two authors throughout the development of the restaurant management system and its accompanying documentation.

== Application Development

=== Yegor Burykin

Yegor Burykin focused primarily on customer-facing features and interactive user interfaces. Major contributions included the complete implementation of the map-based restaurant discovery system, incorporating geolocation services, marker clustering, adaptive radius selection, and bottom sheet navigation. The favorites system, which enabled customers to rank and reorder preferred restaurants using drag-and-drop functionality, was implemented with optimistic updates and transaction-based persistence. Menu item detailed views and cart functionality were developed, including quantity management, item availability checks, and restaurant-specific cart separation. The checkout workflow, spanning order summary generation, payment interface integration, and order placement logic, was implemented with comprehensive validation. Customer order history and detail pages were created with proper status visualization. Profile management functionality for all user roles (customers, restaurant workers, and administrators) was established, handling distinct permission levels. UI components and styling across the application were refined, with particular attention to button variants, form interactions, and mobile responsiveness. The rating and review system was enhanced with real-time recalculation of restaurant ratings based on customer feedback. Database seeding infrastructure was improved with configurable options, progress tracking, and realistic test data generation. Several bug fixes and performance optimizations were applied, including resolution of N+1 query issues and image display problems.

=== Oleksandr Svirin

Oleksandr Svirin concentrated on backend architecture, real-time communication, and documentation infrastructure. The real-time broadcasting system was architected and implemented using Laravel Reverb and WebSocket channels, including private channel authentication, event dispatching for menu item and order updates, and optimistic update patterns on the frontend. The employee-facing application structure was established, including role-based access control, dedicated routing for restaurant administrators and workers, menu management interfaces, and order fulfillment workflows. Database design was formalized, encompassing schema normalization, migration creation, geospatial indexing for location-based queries, and relationship modeling. The review system with image upload capabilities was implemented, integrating Cloudflare R2 for blob storage, image processing workflows, and lightbox display components. Error handling infrastructure was improved across HTTP responses, including custom error pages with role-based redirects and proper exception handling. Search functionality was abstracted into a reusable fuzzy search component using Fuse.js, with configurable weighting and multi-field matching. Development tooling was enhanced through pre-commit hooks for code formatting, VS Code task configurations for rapid PR creation, and improved environment configuration documentation. Several architectural refactoring efforts were completed, including extraction of geospatial logic into a dedicated service class, normalization of menu item relationships, and implementation of accessor patterns for computed attributes.

== Shared Responsibilities

Both authors collaborated on several critical areas. The thesis documentation was jointly developed using Typst, with both contributors authoring chapters on system architecture, implementation details, and technical decisions. Version control practices were maintained collaboratively, with code reviews conducted on all pull requests before merging. Deployment configuration using Docker Compose was refined through paired efforts, ensuring consistency across development and production environments. The development process chapter, covering AI-assisted development, automated workflows, and version control strategies, reflects contributions from both team members.

== Documentation

The complete commit history of the project, demonstrating the detailed breakdown of individual contributions, is available in the project repository @SourceCodeRepo.
